### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by fusion809** [bbarad/atom-pymol-language#1]
I am getting this deprecation error:

Store package settings files in the `settings/` directory instead of `scoped-properties/`

```
Package.loadSettings (/opt/atom/resources/app.asar/src/package.js:584:9)
<unknown> (/opt/atom/resources/app.asar/src/package.js:184:43)
Package.measure (/opt/atom/resources/app.asar/src/package.js:163:15)
Package.load (/opt/atom/resources/app.asar/src/package.js:177:12)
PackageManager.loadPackage (/opt/atom/resources/app.asar/src/package-manager.js:355:14)
PackageManager.loadPackages (/opt/atom/resources/app.asar/src/package-manager.js:325:14)
```

**Comment by bbarad** [comment]
Changing directory name was sufficient to resolve API deprecation.

**Comment by fusion809** [comment]
How do I do this? I am on Ubuntu, keep in mind I am a programming noob so use simple terms (like use the directory names and not some code name that an Atom developer might know, but I won't) please.

**Comment by bbarad** [comment]
Sorry, I should clarify: I have updated this in the atom package manager. Checking for an update should get you the fix automatically. The comment was just a note for me.
